### ISSUE TITLE
Librechat docker install issue

### ISSUE THREAD

**Issue by Tighttempo** [MarkusPfundstein/mcp-obsidian#57]
Hi there! 
I can't seem to make it work in librechat. Al my other mcp servers run well (readwise, filesystem etc.). It runs perfectly in Claude Desktop though. 
Does this have something to do with the certificate for the local rest API?
Librechat runs in docker on my computer.
Thanks so much

**Comment by nikoleesg** [comment]
Hi,
I am facing the same issue. It seems didn't pick up the OBSIDIAN_HOST setting, it still use the default 127.0.0.1, as LibreChat running in docker, the 127.0.0.1 is pointing to docker, not the rest api on host.

**Comment by RalphLemarechal** [comment]
same. does not pick up the OBSIDIAN_HOST and sticks to 127.0.0.1 which fails.

{
  "content": [
    {
      "type": "text",
      "text": "Caught Exception. Error: Request failed: HTTPSConnectionPool(host='127.0.0.1', port=27124): Max retries exceeded with url: /vault// (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fff44019d00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    }
  ],
  "isError": true
}

**Comment by DaftValac** [comment]
I got Librechat working with mcp-obsidian, I can query my notes using OpenRouter models. Unfortunately without an update to this repository, it's not easy for others to get this repo working with Librechat. Luckily the required changes specific to this repo are minimal, just an update to the dependencies in `pyproject.toml`. I'll describe the process to get things working in the meantime.

## Update dependencies

1. In your cloned `mcp-obsidian` repo, modify `pyproject.toml` to update the dependencies.

```toml
# pyproject.toml
[project]
(...)
dependencies = [
 "mcp>=1.12.2", # Updated
 "python-dotenv>=1.0.1",
 "requests>=2.32.4", # Updated
]
```

2. Update your uv lock by running the following inside the repo.

```bash
uv sync --upgrade
```

## Configure Librechat

We need to make changes to two files in order to enable MCP servers and configure Librechat to communicate with mcp-obsidian.

### Setup `docker-compose.override.yml`

1. Copy the example override.

```bash
# Execute inside the cloned Librechat repo
cp docker-compose.override.yml.example docker-compose.override.yml
```

2. Uncomment the `api` service and add a volume so that Librechat can see the mcp-obsidian repo. Be sure to replace `/path/to/repo` with the actual path to your cloned mcp-obsidian repo.

```yaml
# docker-compose.override.yml
services:
  api:
    volumes:
    - type: bind
      source: ./librechat.yaml
      target: /app/librechat.yaml
    - /path/to/repo/mcp-obsidian:/app/mcp-obsidian
```

### Setup `librechat.yaml`

1. Copy the example config.

```bash
# Execute inside the cloned Librechat repo
cp librechat.example.yaml librechat.yaml
```

2. With the "Local REST API" plugin installed in Obsidian, open that plugin's settings and note the API key it gives you. We'll pass this to mcp-obsidian via a parameter in Librechat's configuration yaml.

3. Add the following under the `mcpServers` attribute (can be found as a comment under "Example MCP Servers Object Structure"). Be sure to replace `BOGUS` with the API key given to you by the Obsidian local API plugin.

```yaml
# librechat.yaml
mcpServers:
  mcp-obsidian:
    command: uv
    args:
      - "--directory"
      - "/app/mcp-obsidian"
      - "run"
      - "mcp-obsidian"
    env:
      OBSIDIAN_API_KEY: "BOGUS"
      OBSIDIAN_HOST: "host.docker.internal"  # This is the magic that allows a docker container to connect to the host
      OBSIDIAN_PORT: "27124"
```

## Test

Start Librechat (`docker compose up -d`), select an agent, then turn on the mcp-obsidian tool. If things are configured correctly, you should be able to ask questions about your notes and get answers.

Good luck!
